### ISSUE TITLE
Impossible to create a new account

### ISSUE THREAD

**Issue by nilsenpaul** [printdeal/printdeal-api-rst-docs#54]
I'm trying to create a new account, but get this error (cleared field values in screenshot for privacy reasons):

<img width="586" alt="Scherm­afbeelding 2023-10-26 om 13 25 47" src="https://github.com/printdeal/printdeal-api-rst-docs/assets/6794819/1f4df753-53d9-4a62-84b0-dcb26ef0c496">

**Comment by HaraldVelner** [comment]
Hi @nilsenpaul 

Thanks for reaching out, this issue should be fixed.
Could you try it again?
